[package]
name = "day-12"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
chumsky.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "day-12-bench"
path = "benches/benchmarks.rs"
harness = false
