[package]
name = "day-05"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true


[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "day-05-bench"
path = "benches/benchmarks.rs"
harness = false
